### ISSUE TITLE
Error when working with NextJS 

### ISSUE THREAD

**Issue by robksawyer** [birkir/react-three-gui#15]
I'm getting the following error. 

```
/Users/.../node_modules/react-spring/three.js:1
import * as THREE from 'three';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1116:16)
    at Module._compile (internal/modules/cjs/loader.js:1164:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/Users/.../node_modules/react-three-gui/dist/react-three-gui.cjs.development.js:11:13)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)

```

I was able to fix it by adding the following to my `next.config.js`

```
const withPlugins = require('next-compose-plugins')
const withTM = require('next-transpile-modules')([
  'drei',
  'three',
  'postprocessing',
  'react-three-gui',
  'react-spring/three',
])
...
module.exports = withPlugins(
  [
    [withTM, {}],
    [withFonts, {}],
    [withImages, {}],
    [optimizedImages, {}],
  ],
  nextConfig
)
```

However, now I'm unable to drag the controls around. Hmm... Maybe a z-index issue?

**Comment by robksawyer** [comment]
Fixed it with the following.

```
<div style={{ position: 'relative', zIndex: 100000, }}>
   <Controls />
</div>
```

**Comment by birkir** [comment]
Sounds like you solved this one! Thanks
